//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardHolder.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_Mst
    {
        public int Bank_Id { get; set; }
        public string Bank_nm { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Created_dt { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_dt { get; set; }
        public string Ip_Address { get; set; }
    }
}
