//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardHolder.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class BOBCardEntities : DbContext
    {
        public BOBCardEntities()
            : base("name=BOBCardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CH_ComplaintReason_Mst> CH_ComplaintReason_Mst { get; set; }
        public DbSet<CH_ComplaintTxn_dtl> CH_ComplaintTxn_dtl { get; set; }
        public DbSet<CH_ComplaintType_Mst> CH_ComplaintType_Mst { get; set; }
        public DbSet<CH_Escalation_Mst> CH_Escalation_Mst { get; set; }
        public DbSet<CH_Personalized_Msg> CH_Personalized_Msg { get; set; }
        public DbSet<CH_RequestReason_Mst> CH_RequestReason_Mst { get; set; }
        public DbSet<CH_RequestTxn_dtl> CH_RequestTxn_dtl { get; set; }
        public DbSet<DropDown_Dtl> DropDown_Dtl { get; set; }
        public DbSet<DropDown_Hdr> DropDown_Hdr { get; set; }
        public DbSet<Parameter_Mst> Parameter_Mst { get; set; }
        public DbSet<ELMAH_Error> ELMAH_Error { get; set; }
        public DbSet<CH_Complaint_Escalation> CH_Complaint_Escalation { get; set; }
        public DbSet<CH_Request_Escalation> CH_Request_Escalation { get; set; }
        public DbSet<CH_RequestType_Mst> CH_RequestType_Mst { get; set; }
        public DbSet<Dispatch_Dtl> Dispatch_Dtl { get; set; }
        public DbSet<CH_Complaint_Dtl> CH_Complaint_Dtl { get; set; }
        public DbSet<CH_Complaint_Dtl_log> CH_Complaint_Dtl_log { get; set; }
        public DbSet<Bank_Mst> Bank_Mst { get; set; }
        public DbSet<CH_BobibankingPaymentStatus_Dtl> CH_BobibankingPaymentStatus_Dtl { get; set; }
        public DbSet<CardHolderLogin_Info> CardHolderLogin_Info { get; set; }
        public DbSet<CH_Sessions_Dtl> CH_Sessions_Dtl { get; set; }
        public DbSet<CH_EmailLogger> CH_EmailLogger { get; set; }
        public DbSet<CH_SMSLogger> CH_SMSLogger { get; set; }
        public DbSet<Dispatch_Courier_Rpt> Dispatch_Courier_Rpt { get; set; }
        public DbSet<Dispatch_SpeedPost_Rpt> Dispatch_SpeedPost_Rpt { get; set; }
        public DbSet<Application> Applications { get; set; }
        public DbSet<CardHolder_Mst> CardHolder_Mst { get; set; }
        public DbSet<CH_PaymentStatus_Dtl> CH_PaymentStatus_Dtl { get; set; }
        public DbSet<CH_EMI_Request_Dtl> CH_EMI_Request_Dtl { get; set; }
        public DbSet<CH_Request_Dtl> CH_Request_Dtl { get; set; }
        public DbSet<CH_Request_Dtl_log> CH_Request_Dtl_log { get; set; }
        public DbSet<AuditLog> AuditLogs { get; set; }
    
        public virtual ObjectResult<getCardHolderMst_Result> getCardHolderMst(string user_nm, string publicIP, string localAddress)
        {
            var user_nmParameter = user_nm != null ?
                new ObjectParameter("User_nm", user_nm) :
                new ObjectParameter("User_nm", typeof(string));
    
            var publicIPParameter = publicIP != null ?
                new ObjectParameter("PublicIP", publicIP) :
                new ObjectParameter("PublicIP", typeof(string));
    
            var localAddressParameter = localAddress != null ?
                new ObjectParameter("localAddress", localAddress) :
                new ObjectParameter("localAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCardHolderMst_Result>("getCardHolderMst", user_nmParameter, publicIPParameter, localAddressParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> setCardHolder_Active(Nullable<long> cardHolder_Id)
        {
            var cardHolder_IdParameter = cardHolder_Id.HasValue ?
                new ObjectParameter("CardHolder_Id", cardHolder_Id) :
                new ObjectParameter("CardHolder_Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("setCardHolder_Active", cardHolder_IdParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> setCardHolderMst_Active(Nullable<long> cardHolder_Id)
        {
            var cardHolder_IdParameter = cardHolder_Id.HasValue ?
                new ObjectParameter("CardHolder_Id", cardHolder_Id) :
                new ObjectParameter("CardHolder_Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("setCardHolderMst_Active", cardHolder_IdParameter);
        }
    
        public virtual ObjectResult<GetUserInfoById_Result> GetUserInfoById(Nullable<long> cardHolder_Id)
        {
            var cardHolder_IdParameter = cardHolder_Id.HasValue ?
                new ObjectParameter("CardHolder_Id", cardHolder_Id) :
                new ObjectParameter("CardHolder_Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserInfoById_Result>("GetUserInfoById", cardHolder_IdParameter);
        }
    
        public virtual int deleteCardHolderLogin_Info(Nullable<long> cardHolder_Id)
        {
            var cardHolder_IdParameter = cardHolder_Id.HasValue ?
                new ObjectParameter("CardHolder_Id", cardHolder_Id) :
                new ObjectParameter("CardHolder_Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteCardHolderLogin_Info", cardHolder_IdParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> saveRequestDtl(Nullable<long> request_Dtl_Id, Nullable<System.DateTime> request_Dt, Nullable<long> cardHolder_Id, Nullable<long> requestType_Id, Nullable<long> requestReason_Id, string mode_Send_Statment, Nullable<System.DateTime> dOB, string relation, string gender, string addon_Profile_Photo, string payment_Type, Nullable<decimal> specific_Monthly_due, Nullable<int> points_Wants_Redeem, string bank_nm, Nullable<decimal> transferred_Amt, string balance_Transferred_Plan, Nullable<decimal> eMI_Principal_Amt, Nullable<int> eMI_Terms, Nullable<decimal> eMI_InterestRate, Nullable<decimal> eMI_Amount, string remarks, string request_Status, Nullable<long> created_by, Nullable<System.DateTime> created_dt, Nullable<long> updated_by, Nullable<System.DateTime> updated_dt, string iP_Address, string statement_month, string statement_year, string add_On_Card_Applicant, string otherCreditCardNumber, string hotlistingCardNumber, Nullable<long> user_Id, Nullable<long> action_Id, string uID, string adminRemarks, Nullable<long> mode_Request_Complaint_Id, Nullable<long> finalUpdated_by, Nullable<System.DateTime> finalUpdated_dt, Nullable<int> loan_Terms, Nullable<decimal> loan_InterestRate, Nullable<decimal> loan_Amount, Nullable<decimal> loan_Principal_Amt)
        {
            var request_Dtl_IdParameter = request_Dtl_Id.HasValue ?
                new ObjectParameter("Request_Dtl_Id", request_Dtl_Id) :
                new ObjectParameter("Request_Dtl_Id", typeof(long));
    
            var request_DtParameter = request_Dt.HasValue ?
                new ObjectParameter("Request_Dt", request_Dt) :
                new ObjectParameter("Request_Dt", typeof(System.DateTime));
    
            var cardHolder_IdParameter = cardHolder_Id.HasValue ?
                new ObjectParameter("CardHolder_Id", cardHolder_Id) :
                new ObjectParameter("CardHolder_Id", typeof(long));
    
            var requestType_IdParameter = requestType_Id.HasValue ?
                new ObjectParameter("RequestType_Id", requestType_Id) :
                new ObjectParameter("RequestType_Id", typeof(long));
    
            var requestReason_IdParameter = requestReason_Id.HasValue ?
                new ObjectParameter("RequestReason_Id", requestReason_Id) :
                new ObjectParameter("RequestReason_Id", typeof(long));
    
            var mode_Send_StatmentParameter = mode_Send_Statment != null ?
                new ObjectParameter("Mode_Send_Statment", mode_Send_Statment) :
                new ObjectParameter("Mode_Send_Statment", typeof(string));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var relationParameter = relation != null ?
                new ObjectParameter("Relation", relation) :
                new ObjectParameter("Relation", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var addon_Profile_PhotoParameter = addon_Profile_Photo != null ?
                new ObjectParameter("Addon_Profile_Photo", addon_Profile_Photo) :
                new ObjectParameter("Addon_Profile_Photo", typeof(string));
    
            var payment_TypeParameter = payment_Type != null ?
                new ObjectParameter("Payment_Type", payment_Type) :
                new ObjectParameter("Payment_Type", typeof(string));
    
            var specific_Monthly_dueParameter = specific_Monthly_due.HasValue ?
                new ObjectParameter("Specific_Monthly_due", specific_Monthly_due) :
                new ObjectParameter("Specific_Monthly_due", typeof(decimal));
    
            var points_Wants_RedeemParameter = points_Wants_Redeem.HasValue ?
                new ObjectParameter("Points_Wants_Redeem", points_Wants_Redeem) :
                new ObjectParameter("Points_Wants_Redeem", typeof(int));
    
            var bank_nmParameter = bank_nm != null ?
                new ObjectParameter("Bank_nm", bank_nm) :
                new ObjectParameter("Bank_nm", typeof(string));
    
            var transferred_AmtParameter = transferred_Amt.HasValue ?
                new ObjectParameter("Transferred_Amt", transferred_Amt) :
                new ObjectParameter("Transferred_Amt", typeof(decimal));
    
            var balance_Transferred_PlanParameter = balance_Transferred_Plan != null ?
                new ObjectParameter("Balance_Transferred_Plan", balance_Transferred_Plan) :
                new ObjectParameter("Balance_Transferred_Plan", typeof(string));
    
            var eMI_Principal_AmtParameter = eMI_Principal_Amt.HasValue ?
                new ObjectParameter("EMI_Principal_Amt", eMI_Principal_Amt) :
                new ObjectParameter("EMI_Principal_Amt", typeof(decimal));
    
            var eMI_TermsParameter = eMI_Terms.HasValue ?
                new ObjectParameter("EMI_Terms", eMI_Terms) :
                new ObjectParameter("EMI_Terms", typeof(int));
    
            var eMI_InterestRateParameter = eMI_InterestRate.HasValue ?
                new ObjectParameter("EMI_InterestRate", eMI_InterestRate) :
                new ObjectParameter("EMI_InterestRate", typeof(decimal));
    
            var eMI_AmountParameter = eMI_Amount.HasValue ?
                new ObjectParameter("EMI_Amount", eMI_Amount) :
                new ObjectParameter("EMI_Amount", typeof(decimal));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            var request_StatusParameter = request_Status != null ?
                new ObjectParameter("Request_Status", request_Status) :
                new ObjectParameter("Request_Status", typeof(string));
    
            var created_byParameter = created_by.HasValue ?
                new ObjectParameter("Created_by", created_by) :
                new ObjectParameter("Created_by", typeof(long));
    
            var created_dtParameter = created_dt.HasValue ?
                new ObjectParameter("Created_dt", created_dt) :
                new ObjectParameter("Created_dt", typeof(System.DateTime));
    
            var updated_byParameter = updated_by.HasValue ?
                new ObjectParameter("Updated_by", updated_by) :
                new ObjectParameter("Updated_by", typeof(long));
    
            var updated_dtParameter = updated_dt.HasValue ?
                new ObjectParameter("Updated_dt", updated_dt) :
                new ObjectParameter("Updated_dt", typeof(System.DateTime));
    
            var iP_AddressParameter = iP_Address != null ?
                new ObjectParameter("IP_Address", iP_Address) :
                new ObjectParameter("IP_Address", typeof(string));
    
            var statement_monthParameter = statement_month != null ?
                new ObjectParameter("Statement_month", statement_month) :
                new ObjectParameter("Statement_month", typeof(string));
    
            var statement_yearParameter = statement_year != null ?
                new ObjectParameter("Statement_year", statement_year) :
                new ObjectParameter("Statement_year", typeof(string));
    
            var add_On_Card_ApplicantParameter = add_On_Card_Applicant != null ?
                new ObjectParameter("Add_On_Card_Applicant", add_On_Card_Applicant) :
                new ObjectParameter("Add_On_Card_Applicant", typeof(string));
    
            var otherCreditCardNumberParameter = otherCreditCardNumber != null ?
                new ObjectParameter("OtherCreditCardNumber", otherCreditCardNumber) :
                new ObjectParameter("OtherCreditCardNumber", typeof(string));
    
            var hotlistingCardNumberParameter = hotlistingCardNumber != null ?
                new ObjectParameter("HotlistingCardNumber", hotlistingCardNumber) :
                new ObjectParameter("HotlistingCardNumber", typeof(string));
    
            var user_IdParameter = user_Id.HasValue ?
                new ObjectParameter("User_Id", user_Id) :
                new ObjectParameter("User_Id", typeof(long));
    
            var action_IdParameter = action_Id.HasValue ?
                new ObjectParameter("Action_Id", action_Id) :
                new ObjectParameter("Action_Id", typeof(long));
    
            var uIDParameter = uID != null ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(string));
    
            var adminRemarksParameter = adminRemarks != null ?
                new ObjectParameter("AdminRemarks", adminRemarks) :
                new ObjectParameter("AdminRemarks", typeof(string));
    
            var mode_Request_Complaint_IdParameter = mode_Request_Complaint_Id.HasValue ?
                new ObjectParameter("Mode_Request_Complaint_Id", mode_Request_Complaint_Id) :
                new ObjectParameter("Mode_Request_Complaint_Id", typeof(long));
    
            var finalUpdated_byParameter = finalUpdated_by.HasValue ?
                new ObjectParameter("FinalUpdated_by", finalUpdated_by) :
                new ObjectParameter("FinalUpdated_by", typeof(long));
    
            var finalUpdated_dtParameter = finalUpdated_dt.HasValue ?
                new ObjectParameter("FinalUpdated_dt", finalUpdated_dt) :
                new ObjectParameter("FinalUpdated_dt", typeof(System.DateTime));
    
            var loan_TermsParameter = loan_Terms.HasValue ?
                new ObjectParameter("Loan_Terms", loan_Terms) :
                new ObjectParameter("Loan_Terms", typeof(int));
    
            var loan_InterestRateParameter = loan_InterestRate.HasValue ?
                new ObjectParameter("Loan_InterestRate", loan_InterestRate) :
                new ObjectParameter("Loan_InterestRate", typeof(decimal));
    
            var loan_AmountParameter = loan_Amount.HasValue ?
                new ObjectParameter("Loan_Amount", loan_Amount) :
                new ObjectParameter("Loan_Amount", typeof(decimal));
    
            var loan_Principal_AmtParameter = loan_Principal_Amt.HasValue ?
                new ObjectParameter("Loan_Principal_Amt", loan_Principal_Amt) :
                new ObjectParameter("Loan_Principal_Amt", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("saveRequestDtl", request_Dtl_IdParameter, request_DtParameter, cardHolder_IdParameter, requestType_IdParameter, requestReason_IdParameter, mode_Send_StatmentParameter, dOBParameter, relationParameter, genderParameter, addon_Profile_PhotoParameter, payment_TypeParameter, specific_Monthly_dueParameter, points_Wants_RedeemParameter, bank_nmParameter, transferred_AmtParameter, balance_Transferred_PlanParameter, eMI_Principal_AmtParameter, eMI_TermsParameter, eMI_InterestRateParameter, eMI_AmountParameter, remarksParameter, request_StatusParameter, created_byParameter, created_dtParameter, updated_byParameter, updated_dtParameter, iP_AddressParameter, statement_monthParameter, statement_yearParameter, add_On_Card_ApplicantParameter, otherCreditCardNumberParameter, hotlistingCardNumberParameter, user_IdParameter, action_IdParameter, uIDParameter, adminRemarksParameter, mode_Request_Complaint_IdParameter, finalUpdated_byParameter, finalUpdated_dtParameter, loan_TermsParameter, loan_InterestRateParameter, loan_AmountParameter, loan_Principal_AmtParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> saveComplaintDtl(Nullable<long> complaint_Dtl_Id, Nullable<System.DateTime> complaint_Dt, Nullable<long> cardHolder_Id, Nullable<long> complaintType_Id, string remarks, string complaint_Status, Nullable<long> created_by, Nullable<System.DateTime> created_dt, Nullable<long> updated_by, Nullable<System.DateTime> updated_dt, string iP_Address, Nullable<long> user_Id, Nullable<long> action_Id, string uID, string adminRemarks, Nullable<long> mode_Request_Complaint_Id, Nullable<long> finalUpdated_by, Nullable<System.DateTime> finalUpdated_dt)
        {
            var complaint_Dtl_IdParameter = complaint_Dtl_Id.HasValue ?
                new ObjectParameter("Complaint_Dtl_Id", complaint_Dtl_Id) :
                new ObjectParameter("Complaint_Dtl_Id", typeof(long));
    
            var complaint_DtParameter = complaint_Dt.HasValue ?
                new ObjectParameter("Complaint_Dt", complaint_Dt) :
                new ObjectParameter("Complaint_Dt", typeof(System.DateTime));
    
            var cardHolder_IdParameter = cardHolder_Id.HasValue ?
                new ObjectParameter("CardHolder_Id", cardHolder_Id) :
                new ObjectParameter("CardHolder_Id", typeof(long));
    
            var complaintType_IdParameter = complaintType_Id.HasValue ?
                new ObjectParameter("ComplaintType_Id", complaintType_Id) :
                new ObjectParameter("ComplaintType_Id", typeof(long));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            var complaint_StatusParameter = complaint_Status != null ?
                new ObjectParameter("Complaint_Status", complaint_Status) :
                new ObjectParameter("Complaint_Status", typeof(string));
    
            var created_byParameter = created_by.HasValue ?
                new ObjectParameter("Created_by", created_by) :
                new ObjectParameter("Created_by", typeof(long));
    
            var created_dtParameter = created_dt.HasValue ?
                new ObjectParameter("Created_dt", created_dt) :
                new ObjectParameter("Created_dt", typeof(System.DateTime));
    
            var updated_byParameter = updated_by.HasValue ?
                new ObjectParameter("Updated_by", updated_by) :
                new ObjectParameter("Updated_by", typeof(long));
    
            var updated_dtParameter = updated_dt.HasValue ?
                new ObjectParameter("Updated_dt", updated_dt) :
                new ObjectParameter("Updated_dt", typeof(System.DateTime));
    
            var iP_AddressParameter = iP_Address != null ?
                new ObjectParameter("IP_Address", iP_Address) :
                new ObjectParameter("IP_Address", typeof(string));
    
            var user_IdParameter = user_Id.HasValue ?
                new ObjectParameter("User_Id", user_Id) :
                new ObjectParameter("User_Id", typeof(long));
    
            var action_IdParameter = action_Id.HasValue ?
                new ObjectParameter("Action_Id", action_Id) :
                new ObjectParameter("Action_Id", typeof(long));
    
            var uIDParameter = uID != null ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(string));
    
            var adminRemarksParameter = adminRemarks != null ?
                new ObjectParameter("AdminRemarks", adminRemarks) :
                new ObjectParameter("AdminRemarks", typeof(string));
    
            var mode_Request_Complaint_IdParameter = mode_Request_Complaint_Id.HasValue ?
                new ObjectParameter("Mode_Request_Complaint_Id", mode_Request_Complaint_Id) :
                new ObjectParameter("Mode_Request_Complaint_Id", typeof(long));
    
            var finalUpdated_byParameter = finalUpdated_by.HasValue ?
                new ObjectParameter("FinalUpdated_by", finalUpdated_by) :
                new ObjectParameter("FinalUpdated_by", typeof(long));
    
            var finalUpdated_dtParameter = finalUpdated_dt.HasValue ?
                new ObjectParameter("FinalUpdated_dt", finalUpdated_dt) :
                new ObjectParameter("FinalUpdated_dt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("saveComplaintDtl", complaint_Dtl_IdParameter, complaint_DtParameter, cardHolder_IdParameter, complaintType_IdParameter, remarksParameter, complaint_StatusParameter, created_byParameter, created_dtParameter, updated_byParameter, updated_dtParameter, iP_AddressParameter, user_IdParameter, action_IdParameter, uIDParameter, adminRemarksParameter, mode_Request_Complaint_IdParameter, finalUpdated_byParameter, finalUpdated_dtParameter);
        }
    
        public virtual ObjectResult<string> getComplaintUID(Nullable<long> complaint_Dtl_Id)
        {
            var complaint_Dtl_IdParameter = complaint_Dtl_Id.HasValue ?
                new ObjectParameter("Complaint_Dtl_Id", complaint_Dtl_Id) :
                new ObjectParameter("Complaint_Dtl_Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getComplaintUID", complaint_Dtl_IdParameter);
        }
    
        public virtual ObjectResult<string> getRequestUID(Nullable<long> request_Dtl_Id)
        {
            var request_Dtl_IdParameter = request_Dtl_Id.HasValue ?
                new ObjectParameter("Request_Dtl_Id", request_Dtl_Id) :
                new ObjectParameter("Request_Dtl_Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getRequestUID", request_Dtl_IdParameter);
        }
    
        public virtual ObjectResult<getComplaint_UID_Result> getComplaint_UID(Nullable<long> complaint_Dtl_Id)
        {
            var complaint_Dtl_IdParameter = complaint_Dtl_Id.HasValue ?
                new ObjectParameter("Complaint_Dtl_Id", complaint_Dtl_Id) :
                new ObjectParameter("Complaint_Dtl_Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getComplaint_UID_Result>("getComplaint_UID", complaint_Dtl_IdParameter);
        }
    
        public virtual ObjectResult<getRequest_UID_Result> getRequest_UID(Nullable<long> request_Dtl_Id)
        {
            var request_Dtl_IdParameter = request_Dtl_Id.HasValue ?
                new ObjectParameter("Request_Dtl_Id", request_Dtl_Id) :
                new ObjectParameter("Request_Dtl_Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRequest_UID_Result>("getRequest_UID", request_Dtl_IdParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> saveAuditLog(Nullable<long> id, Nullable<long> requestType_Id, Nullable<long> cardHolder_Id, string txnType, string credit_card_number, string requestReason, string txnReferenceNo, string responseStatus, Nullable<long> created_by, Nullable<System.DateTime> created_dt, Nullable<long> updated_by, Nullable<System.DateTime> updated_dt, string bankRefNo, string iP_Address)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            var requestType_IdParameter = requestType_Id.HasValue ?
                new ObjectParameter("RequestType_Id", requestType_Id) :
                new ObjectParameter("RequestType_Id", typeof(long));
    
            var cardHolder_IdParameter = cardHolder_Id.HasValue ?
                new ObjectParameter("CardHolder_Id", cardHolder_Id) :
                new ObjectParameter("CardHolder_Id", typeof(long));
    
            var txnTypeParameter = txnType != null ?
                new ObjectParameter("TxnType", txnType) :
                new ObjectParameter("TxnType", typeof(string));
    
            var credit_card_numberParameter = credit_card_number != null ?
                new ObjectParameter("Credit_card_number", credit_card_number) :
                new ObjectParameter("Credit_card_number", typeof(string));
    
            var requestReasonParameter = requestReason != null ?
                new ObjectParameter("RequestReason", requestReason) :
                new ObjectParameter("RequestReason", typeof(string));
    
            var txnReferenceNoParameter = txnReferenceNo != null ?
                new ObjectParameter("TxnReferenceNo", txnReferenceNo) :
                new ObjectParameter("TxnReferenceNo", typeof(string));
    
            var responseStatusParameter = responseStatus != null ?
                new ObjectParameter("ResponseStatus", responseStatus) :
                new ObjectParameter("ResponseStatus", typeof(string));
    
            var created_byParameter = created_by.HasValue ?
                new ObjectParameter("Created_by", created_by) :
                new ObjectParameter("Created_by", typeof(long));
    
            var created_dtParameter = created_dt.HasValue ?
                new ObjectParameter("Created_dt", created_dt) :
                new ObjectParameter("Created_dt", typeof(System.DateTime));
    
            var updated_byParameter = updated_by.HasValue ?
                new ObjectParameter("Updated_by", updated_by) :
                new ObjectParameter("Updated_by", typeof(long));
    
            var updated_dtParameter = updated_dt.HasValue ?
                new ObjectParameter("Updated_dt", updated_dt) :
                new ObjectParameter("Updated_dt", typeof(System.DateTime));
    
            var bankRefNoParameter = bankRefNo != null ?
                new ObjectParameter("BankRefNo", bankRefNo) :
                new ObjectParameter("BankRefNo", typeof(string));
    
            var iP_AddressParameter = iP_Address != null ?
                new ObjectParameter("IP_Address", iP_Address) :
                new ObjectParameter("IP_Address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("saveAuditLog", idParameter, requestType_IdParameter, cardHolder_IdParameter, txnTypeParameter, credit_card_numberParameter, requestReasonParameter, txnReferenceNoParameter, responseStatusParameter, created_byParameter, created_dtParameter, updated_byParameter, updated_dtParameter, bankRefNoParameter, iP_AddressParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> getCheckPendingRequestCount(Nullable<long> cardHolder_Id, Nullable<long> requestType_Id, string request_Status)
        {
            var cardHolder_IdParameter = cardHolder_Id.HasValue ?
                new ObjectParameter("CardHolder_Id", cardHolder_Id) :
                new ObjectParameter("CardHolder_Id", typeof(long));
    
            var requestType_IdParameter = requestType_Id.HasValue ?
                new ObjectParameter("RequestType_Id", requestType_Id) :
                new ObjectParameter("RequestType_Id", typeof(long));
    
            var request_StatusParameter = request_Status != null ?
                new ObjectParameter("Request_Status", request_Status) :
                new ObjectParameter("Request_Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("getCheckPendingRequestCount", cardHolder_IdParameter, requestType_IdParameter, request_StatusParameter);
        }
    
        public virtual ObjectResult<getStatusRecord_Result> getStatusRecord(Nullable<long> cardholderId)
        {
            var cardholderIdParameter = cardholderId.HasValue ?
                new ObjectParameter("cardholderId", cardholderId) :
                new ObjectParameter("cardholderId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getStatusRecord_Result>("getStatusRecord", cardholderIdParameter);
        }
    
        public virtual ObjectResult<getRequestStatusRecord_Result> getRequestStatusRecord(Nullable<long> cardholderId)
        {
            var cardholderIdParameter = cardholderId.HasValue ?
                new ObjectParameter("cardholderId", cardholderId) :
                new ObjectParameter("cardholderId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRequestStatusRecord_Result>("getRequestStatusRecord", cardholderIdParameter);
        }
    }
}
