//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardHolder.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardHolder_Mst
    {
        public CardHolder_Mst()
        {
            this.CH_Complaint_Dtl = new HashSet<CH_Complaint_Dtl>();
            this.CH_Personalized_Msg = new HashSet<CH_Personalized_Msg>();
            this.Dispatch_Dtl = new HashSet<Dispatch_Dtl>();
            this.CH_Request_Dtl = new HashSet<CH_Request_Dtl>();
        }
    
        public long CardHolder_Id { get; set; }
        public long Oracle_Customer_Id { get; set; }
        public string User_nm { get; set; }
        public string User_pwd { get; set; }
        public string UID { get; set; }
        public string Profile_Photo { get; set; }
        public string AddOn1_Photo { get; set; }
        public string AddOn2_Photo { get; set; }
        public string AddOn3_Photo { get; set; }
        public string Personal_Msg { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsPermanentDisable { get; set; }
        public Nullable<bool> IsLoggedIn { get; set; }
        public long Created_by { get; set; }
        public System.DateTime Created_dt { get; set; }
        public Nullable<long> Updated_by { get; set; }
        public Nullable<System.DateTime> Updated_dt { get; set; }
        public string IP_Address { get; set; }
        public string Local_IpAddress { get; set; }
        public string credit_card_number { get; set; }
        public string creditcard_acc_number { get; set; }
        public Nullable<bool> IsLoggedInCurrently { get; set; }
        public Nullable<System.DateTime> InvalidLastLoginDt { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> CurrentLoginDate { get; set; }
    
        public virtual ICollection<CH_Complaint_Dtl> CH_Complaint_Dtl { get; set; }
        public virtual ICollection<CH_Personalized_Msg> CH_Personalized_Msg { get; set; }
        public virtual ICollection<Dispatch_Dtl> Dispatch_Dtl { get; set; }
        public virtual ICollection<CH_Request_Dtl> CH_Request_Dtl { get; set; }
    }
}
