//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardHolder.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH_Complaint_Dtl
    {
        public CH_Complaint_Dtl()
        {
            this.CH_ComplaintTxn_dtl = new HashSet<CH_ComplaintTxn_dtl>();
        }
    
        public long Complaint_Dtl_Id { get; set; }
        public System.DateTime Complaint_Dt { get; set; }
        public long CardHolder_Id { get; set; }
        public long ComplaintType_Id { get; set; }
        public string Remarks { get; set; }
        public string Complaint_Status { get; set; }
        public long Created_by { get; set; }
        public System.DateTime Created_dt { get; set; }
        public Nullable<long> Updated_by { get; set; }
        public Nullable<System.DateTime> Updated_dt { get; set; }
        public string IP_Address { get; set; }
        public Nullable<long> User_Id { get; set; }
        public Nullable<long> Action_Id { get; set; }
        public string UID { get; set; }
        public string AdminRemarks { get; set; }
        public Nullable<long> Mode_Request_Complaint_Id { get; set; }
        public Nullable<long> FinalUpdated_by { get; set; }
        public Nullable<System.DateTime> FinalUpdated_dt { get; set; }
    
        public virtual CH_ComplaintType_Mst CH_ComplaintType_Mst { get; set; }
        public virtual ICollection<CH_ComplaintTxn_dtl> CH_ComplaintTxn_dtl { get; set; }
        public virtual CardHolder_Mst CardHolder_Mst { get; set; }
    }
}
