//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardHolder.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH_Escalation_Mst
    {
        public CH_Escalation_Mst()
        {
            this.CH_ComplaintTxn_dtl = new HashSet<CH_ComplaintTxn_dtl>();
            this.CH_RequestTxn_dtl = new HashSet<CH_RequestTxn_dtl>();
            this.CH_Complaint_Escalation = new HashSet<CH_Complaint_Escalation>();
            this.CH_Request_Escalation = new HashSet<CH_Request_Escalation>();
        }
    
        public long Escalation_Id { get; set; }
        public int Escalation_Level { get; set; }
        public long Created_by { get; set; }
        public System.DateTime Created_dt { get; set; }
        public Nullable<long> Updated_by { get; set; }
        public Nullable<System.DateTime> Updated_dt { get; set; }
        public string IP_Address { get; set; }
    
        public virtual ICollection<CH_ComplaintTxn_dtl> CH_ComplaintTxn_dtl { get; set; }
        public virtual ICollection<CH_RequestTxn_dtl> CH_RequestTxn_dtl { get; set; }
        public virtual ICollection<CH_Complaint_Escalation> CH_Complaint_Escalation { get; set; }
        public virtual ICollection<CH_Request_Escalation> CH_Request_Escalation { get; set; }
    }
}
