//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardHolder.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH_Personalized_Msg
    {
        public long Personalized_Msg_Id { get; set; }
        public System.DateTime Personalized_Msg_Dt { get; set; }
        public string Personalized_Msg { get; set; }
        public long CardHolder_Id { get; set; }
        public Nullable<System.DateTime> Publish_Dt { get; set; }
        public Nullable<System.DateTime> Expiry_Dt { get; set; }
        public long Created_by { get; set; }
        public System.DateTime Created_dt { get; set; }
        public Nullable<long> Updated_by { get; set; }
        public Nullable<System.DateTime> Updated_dt { get; set; }
        public string IP_Address { get; set; }
    
        public virtual CardHolder_Mst CardHolder_Mst { get; set; }
    }
}
