//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardHolder.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH_PaymentStatus_Dtl
    {
        public long PaymentStatus_Id { get; set; }
        public string Creditcard_acc_number { get; set; }
        public string Credit_card_number { get; set; }
        public string Transaction_number { get; set; }
        public string TxnReferenceNo { get; set; }
        public double AmountDue { get; set; }
        public string PaymentStatus { get; set; }
        public long Created_by { get; set; }
        public System.DateTime Created_dt { get; set; }
        public Nullable<long> Updated_by { get; set; }
        public Nullable<System.DateTime> Updated_dt { get; set; }
        public string IP_Address { get; set; }
        public string BillDeskOnlineID { get; set; }
        public string BankRefNo { get; set; }
        public string BankId { get; set; }
        public string AuthStatus { get; set; }
    }
}
