//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardHolder.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH_RequestReason_Mst
    {
        public CH_RequestReason_Mst()
        {
            this.CH_Request_Dtl = new HashSet<CH_Request_Dtl>();
        }
    
        public long RequestReason_Id { get; set; }
        public long RequestType_Id { get; set; }
        public string Reason_nm { get; set; }
        public long Created_by { get; set; }
        public System.DateTime Created_dt { get; set; }
        public Nullable<long> Updated_by { get; set; }
        public Nullable<System.DateTime> Updated_dt { get; set; }
        public string IP_Address { get; set; }
    
        public virtual CH_RequestType_Mst CH_RequestType_Mst { get; set; }
        public virtual ICollection<CH_Request_Dtl> CH_Request_Dtl { get; set; }
    }
}
