//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardHolder.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH_RequestType_Mst
    {
        public CH_RequestType_Mst()
        {
            this.CH_RequestReason_Mst = new HashSet<CH_RequestReason_Mst>();
            this.CH_Request_Dtl = new HashSet<CH_Request_Dtl>();
        }
    
        public long RequestType_Id { get; set; }
        public Nullable<int> Dept_Id { get; set; }
        public string RequestType_nm { get; set; }
        public string RequestType_Desc { get; set; }
        public Nullable<bool> IsStandard { get; set; }
        public long Created_by { get; set; }
        public System.DateTime Created_dt { get; set; }
        public Nullable<long> Updated_by { get; set; }
        public Nullable<System.DateTime> Updated_dt { get; set; }
        public string IP_Address { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<CH_RequestReason_Mst> CH_RequestReason_Mst { get; set; }
        public virtual ICollection<CH_Request_Dtl> CH_Request_Dtl { get; set; }
    }
}
