//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardHolder.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH_Request_Escalation
    {
        public long RequestType_Id { get; set; }
        public long Escalation_Id { get; set; }
        public int Escalation_hrs { get; set; }
        public long Created_by { get; set; }
        public System.DateTime Created_dt { get; set; }
        public Nullable<long> Updated_by { get; set; }
        public Nullable<System.DateTime> Updated_dt { get; set; }
        public string IP_Address { get; set; }
        public long id { get; set; }
        public Nullable<long> user_id { get; set; }
        public Nullable<int> Starthours { get; set; }
        public Nullable<int> Endhours { get; set; }
    
        public virtual CH_Escalation_Mst CH_Escalation_Mst { get; set; }
    }
}
