//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardHolder.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatch_SpeedPost_Rpt
    {
        public string Reference_No { get; set; }
        public string MailingName { get; set; }
        public string COName_on_Primary_Card { get; set; }
        public string MailingAddress1 { get; set; }
        public string MailingAddress2 { get; set; }
        public string MailingAddress3 { get; set; }
        public string MailingAddress4 { get; set; }
        public string MailingCity { get; set; }
        public string MailingPincode { get; set; }
        public string MailingCountry { get; set; }
        public string MailingPhone { get; set; }
        public string MailingMobile { get; set; }
        public string MailingEmail { get; set; }
        public string BATCH_NUMBER { get; set; }
        public string REQUEST_TYPE { get; set; }
        public string Courier { get; set; }
        public string DISPATCH_DATE { get; set; }
        public string Awb_No { get; set; }
        public string Delivery_Status { get; set; }
        public string CARD_PIN { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public Nullable<long> UpdatedApprovedBy { get; set; }
        public Nullable<System.DateTime> UpdatedApprovedOn { get; set; }
        public Nullable<long> FId { get; set; }
    }
}
