//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardHolder.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatch_Courier_Rpt
    {
        public string CAWBNO { get; set; }
        public string CCRCRDREF { get; set; }
        public string DPUDATEFCH { get; set; }
        public string CORGDESC { get; set; }
        public string CDSTDESC { get; set; }
        public string CCNEENAME { get; set; }
        public string CSTATDESC { get; set; }
        public string CQRYGRP { get; set; }
        public string DSTATDATE { get; set; }
        public string CSTATTIME { get; set; }
        public string CRECPID { get; set; }
        public string CRELATION { get; set; }
        public string CIDTYPE { get; set; }
        public string CIDNO { get; set; }
        public string CORGAREA { get; set; }
        public string CCUSTCODE { get; set; }
        public string NWEIGHT { get; set; }
        public string CPUTIME { get; set; }
        public string NPCS { get; set; }
        public string DEPTDTDLV { get; set; }
        public string CSPLINST { get; set; }
        public string NEWAWBNO { get; set; }
        public string CSENDER { get; set; }
        public string CRTOREASON { get; set; }
        public string CPRODCODE { get; set; }
        public string CPRODTYPE { get; set; }
        public string CARD_PIN { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public Nullable<long> UpdatedApprovedBy { get; set; }
        public Nullable<System.DateTime> UpdatedApprovedOn { get; set; }
        public long FId { get; set; }
    }
}
