//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardHolder.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter_Mst
    {
        public int Parameter_Id { get; set; }
        public string Parameter_Name { get; set; }
        public string Parameter_Data_Type { get; set; }
        public string Parameter_ValueC { get; set; }
        public Nullable<decimal> Parameter_ValueD { get; set; }
        public Nullable<long> Parameter_ValueN { get; set; }
        public long Created_by { get; set; }
        public System.DateTime Created_dt { get; set; }
        public Nullable<long> Updated_by { get; set; }
        public Nullable<System.DateTime> Updated_dt { get; set; }
        public string IP_Address { get; set; }
        public string Parameter_Val_StaffC { get; set; }
        public Nullable<decimal> Parameter_Val_StaffD { get; set; }
        public Nullable<long> Parameter_Val_StaffN { get; set; }
    }
}
