using System;

namespace CardHolder.DTO
{
    public class Application_DTO
    {
        public System.Int32 ID { get; set; }
        public System.String APPLICATION_NO { get; set; }
        public System.String SOURCE_APPLICATION_NO { get; set; }
        public System.String SOURCE_TYPE { get; set; }
        public System.String SOURCE_CODE { get; set; }
        public System.String BANK_CODE { get; set; }
        public System.String PRODUCT_CODE { get; set; }
        public Nullable<System.Int32> VIP_CODE { get; set; }
        public System.String SOCIAL_STATUS { get; set; }
        public System.String BASIC_CARD_FLAG { get; set; }
        public System.String PRIMARY_CARD_NUMBER { get; set; }
        public System.String CLIENT_ID_OF_COMPANY { get; set; }
        public System.String TITLE { get; set; }
        public System.String FAMILY_NAME { get; set; }
        public System.String FIRST_NAME { get; set; }
        public System.String EMBOSSED_NAME { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public System.String BIRTH_CITY { get; set; }
        public System.String BIRTH_COUNTRY { get; set; }
        public System.String GENDER { get; set; }
        public Nullable<System.Int32> MARITAL_STATUS { get; set; }
        public Nullable<System.Int32> NO_OF_DEPENDENTS { get; set; }
        public System.String NATIONALITY { get; set; }
        public System.String PERM_ADDRESS1 { get; set; }
        public System.String PERM_ADDRESS2 { get; set; }
        public System.String PERM_ADDRESS3 { get; set; }
        public System.String PERM_ADDRESS4 { get; set; }
        public System.String PERM_POSTAL_CODE { get; set; }
        public System.String PERM_CITY_CODE { get; set; }
        public System.String PERM_COUNTRY_CODE { get; set; }
        public Nullable<System.Int32> RESIDENCE_STATUS { get; set; }
        public System.String CURR_ADDRESS1 { get; set; }
        public System.String CURR_ADDRESS2 { get; set; }
        public System.String CURR_ADDRESS3 { get; set; }
        public System.String CURR_ADDRESS4 { get; set; }
        public System.String CURR_POSTAL_CODE { get; set; }
        public System.String CURR_CITY_CODE { get; set; }
        public System.String CURR_COUNTRY_CODE { get; set; }
        public System.String HOME_PHONE_NUMBER { get; set; }
        public System.String OFFICE_PHONE_NUMBER { get; set; }
        public System.String MOBILE_NUMBER { get; set; }
        public System.String EMAIL_ID { get; set; }
        public Nullable<System.Int32> EDUCATION { get; set; }
        public Nullable<System.Int32> EMPLOYMENT_STATUS { get; set; }
        public Nullable<System.Int32> COMP_TYPE { get; set; }
        public Nullable<System.Int32> APPLICANT_PROF { get; set; }
        public System.String EMPLOYER_NAME { get; set; }
        public System.String EMPL_ADDRESS1 { get; set; }
        public System.String EMPL_ADDRESS2 { get; set; }
        public System.String EMPL_ADDRESS3 { get; set; }
        public System.String EMPL_ADDRESS4 { get; set; }
        public System.String EMPL_POSTAL_CODE { get; set; }
        public System.String EMPL_CITY_CODE { get; set; }
        public System.String EMPL_COUNTRY_CODE { get; set; }
        public System.String EXISTING_CREDIT_CARD_NUMBER { get; set; }
        public Nullable<System.Int32> ACC_IN_BANK { get; set; }
        public System.String ACCOUNT_BRANCH { get; set; }
        public System.String ACCOUNT_NUMBER { get; set; }
        public Nullable<System.Int32> OWNED_VEHICLE_TYPE { get; set; }
        public Nullable<System.Int32> ANNUAL_INCOME_CODE { get; set; }
        public System.String INSURANCE_NOM_NAME { get; set; }
        public System.String INSURANCE_NOM_REL { get; set; }
        public System.String PAN_GIR_NO { get; set; }
        public System.String PASSPORT_NUMBER { get; set; }
        public System.String DRIVING_LICENSE_NUMBER { get; set; }
        public System.String PASSPORT_PLACE_OF_ISSUE { get; set; }
        public System.String ADDITIONAL_CARD_NAME { get; set; }
        public System.String ADDITIONAL_CARD_EMB_NAME { get; set; }
        public System.String ADDITIONAL_CARD_REL { get; set; }
        public System.String APPLICATION_STATUS { get; set; }
        public System.String CLIENT_CODE { get; set; }
        public System.String CARD_NUMBER { get; set; }
        public Nullable<System.Int64> BATCH_NUMBER { get; set; }
        public System.String RISK_STATUS { get; set; }
        public Nullable<System.Int32> CREDIT_LIMIT { get; set; }
        public System.String CURRENCY_CODE { get; set; }
        public Nullable<System.DateTime> APP_PROCESS_DATE { get; set; }
        public Nullable<System.Int32> SCORE { get; set; }
        public Nullable<System.Int32> AGE { get; set; }
        public System.String REMARKS { get; set; }
        public Nullable<System.Int32> REASON_CODE { get; set; }
        public System.String USER_CREATE { get; set; }
        public Nullable<System.DateTime> DATE_CREATE { get; set; }
        public System.String USER_MODIF { get; set; }
        public Nullable<System.DateTime> DATE_MODIF { get; set; }
        public System.String USER_DELETE { get; set; }
        public Nullable<System.DateTime> DATE_DELETE { get; set; }
        public System.String LANGUAGE_PREF { get; set; }
        public System.String MAIDEN_NAME { get; set; }
        public System.String PREFERENCES { get; set; }
        public System.String SEC_CARD_NUMBER { get; set; }
        public System.String CR_ACCOUNT_NBR { get; set; }
        public System.String PHOTOCARD_APP_IND { get; set; }
        public System.String BT_IND { get; set; }
        public System.String BT_BANK { get; set; }
        public System.String BT_CARD { get; set; }
        public Nullable<System.Int32> BT_AMOUNT { get; set; }
        public Nullable<System.Double> BT_INTEREST_RATE { get; set; }
        public Nullable<System.DateTime> SEC_BIRTH_DATE { get; set; }
        public System.String USER_VERIF { get; set; }
        public Nullable<System.DateTime> DATE_VERIFY { get; set; }
        public System.String USER_APPROVED { get; set; }
        public Nullable<System.DateTime> DATE_APPROVED { get; set; }
        public System.String USER_APPROVED_SATYAM { get; set; }
        public Nullable<System.DateTime> DATE_APPROVED_SATYAM { get; set; }
        public System.String SATYAM_FILE { get; set; }
        public System.String ADDITIONAL_FAMILY_NAME { get; set; }
        public System.String EMBOSSED_LINE_4 { get; set; }
        public Nullable<System.Int32> CASH_LIMIT { get; set; }
        public System.String SEC_TITLE { get; set; }
        public System.String SPOUSE_NAME { get; set; }
        public Nullable<System.Double> SPOUSE_INCOME { get; set; }
        public Nullable<System.Int32> PERMNANT_ADDRESS_TENURE { get; set; }
        public Nullable<System.Int32> MAILING_ADDRESS_TENURE { get; set; }
        public System.String PASSWORD { get; set; }
        public System.String EMPLOYER_BUSINESS_NATURE { get; set; }
        public Nullable<System.Int32> CURRENT_JOB_TENURE { get; set; }
        public System.String PREVIOUS_EMPLOYER_NAME { get; set; }
        public Nullable<System.Int32> PREVIOUS_JOB_TENURE { get; set; }
        public Nullable<System.Int32> WORKPLACE { get; set; }
        public System.String OUR_ACCOUNT_TYPE { get; set; }
        public Nullable<System.Int32> OUR_ACCOUNT_TENURE { get; set; }
        public Nullable<System.Int32> OUR_ACCOUNT_STATUS { get; set; }
        public Nullable<System.Int32> OUR_BANK_ACC_AVERAGE_BALANCES { get; set; }
        public System.String OTHER_BANK_NAME { get; set; }
        public System.String OTHER_ACCOUNT_TYPE { get; set; }
        public System.String OTHER_ACCOUNT_NUMBER { get; set; }
        public Nullable<System.Int32> OTHER_ACCOUNT_TENURE { get; set; }
        public Nullable<System.Int32> OTHER_ACCOUNT_STATUS { get; set; }
        public Nullable<System.Int32> OTHER_BANK_ACC_AVG_BALANCES { get; set; }
        public Nullable<System.Double> HOME_ESTIMATED_CURRENT_VALUE { get; set; }
        public Nullable<System.Double> HOME_CURR_MORTGAGE_OUTSTANDING { get; set; }
        public Nullable<System.Double> HOME_MONTHLY_MORTGAGE_REPAY { get; set; }
        public System.String HSG_LENDER_NAME { get; set; }
        public System.String HSG_LENDER_ADDRESS1 { get; set; }
        public System.String HSG_LENDER_ADDRESS2 { get; set; }
        public System.String HSG_LENDER_ADDRESS3 { get; set; }
        public System.String HSG_LENDER_ADDRESS4 { get; set; }
        public System.String HSG_LENDER_ZIP_CODE { get; set; }
        public System.String HSG_LENDER_CITY_CODE { get; set; }
        public System.String HSG_LENDER_COUNTRY_CODE { get; set; }
        public System.String HSG_LENDER_PHONE_NUMBER { get; set; }
        public System.String HSG_LENDER_ACCOUNT_NUMBER { get; set; }
        public Nullable<System.Double> HOME_MONTHLY_RENT { get; set; }
        public System.String OTHER_LOAN { get; set; }
        public System.String OTHER_LOAN_DESC { get; set; }
        public System.String OTHER_LENDER1_NAME { get; set; }
        public System.String OTHER_LENDER1_ADDRESS1 { get; set; }
        public System.String OTHER_LENDER1_ADDRESS2 { get; set; }
        public System.String OTHER_LENDER1_ADDRESS3 { get; set; }
        public System.String OTHER_LENDER1_ADDRESS4 { get; set; }
        public System.String OTHER_LENDER1_ZIP_CODE { get; set; }
        public System.String OTHER_LENDER1_CITY_CODE { get; set; }
        public System.String OTHER_LENDER1_COUNTRY_CODE { get; set; }
        public System.String OTHER_LENDER1_PHONE_NUMBER { get; set; }
        public Nullable<System.Double> OTHER_LENDER1_MONTHLY_PAYMENT { get; set; }
        public Nullable<System.Double> OTHER_LENDER1_CURRENT_BALANCE { get; set; }
        public System.String OTHER_LENDER2_NAME { get; set; }
        public System.String OTHER_LENDER2_ADDRESS1 { get; set; }
        public System.String OTHER_LENDER2_ADDRESS2 { get; set; }
        public System.String OTHER_LENDER2_ADDRESS3 { get; set; }
        public System.String OTHER_LENDER2_ADDRESS4 { get; set; }
        public System.String OTHER_LENDER2_ZIP_CODE { get; set; }
        public System.String OTHER_LENDER2_CITY_CODE { get; set; }
        public System.String OTHER_LENDER2_COUNTRY_CODE { get; set; }
        public System.String OTHER_LENDER2_PHONE_NUMBER { get; set; }
        public Nullable<System.Double> OTHER_LENDER2_MONTHLY_PAYMENT { get; set; }
        public Nullable<System.Double> OTHER_LENDER2_CURRENT_BALANCE { get; set; }
        public Nullable<System.Int32> OTHER_CREDIT_CARDS_TYPE { get; set; }
        public Nullable<System.Int32> OTHER_CREDIT_CARDS_COUNT { get; set; }
        public System.String CARD1_ISSUED_BY { get; set; }
        public Nullable<System.Int32> CARD1_TENURE { get; set; }
        public Nullable<System.Int32> CARD1_REFERENCES { get; set; }
        public System.String CARD2_ISSUED_BY { get; set; }
        public System.String CARD2_NUMBER { get; set; }
        public Nullable<System.Int32> CARD2_TENURE { get; set; }
        public Nullable<System.Int32> CARD2_REFERENCES { get; set; }
        public Nullable<System.Double> MONTHLY_REPAYMENTS_TO_LOAN { get; set; }
        public System.String REF1_NAME { get; set; }
        public System.String REF1_ADDRESS1 { get; set; }
        public System.String REF1_ADDRESS2 { get; set; }
        public System.String REF1_ADDRESS3 { get; set; }
        public System.String REF1_ADDRESS4 { get; set; }
        public System.String REF1_ZIP_CODE { get; set; }
        public System.String REF1_CITY_CODE { get; set; }
        public System.String REF1_COUNTRY_CODE { get; set; }
        public System.String REF1_PHONE_NUMBER { get; set; }
        public System.String REF2_NAME { get; set; }
        public System.String REF2_ADDRESS1 { get; set; }
        public System.String REF2_ADDRESS2 { get; set; }
        public System.String REF2_ADDRESS3 { get; set; }
        public System.String REF2_ADDRESS4 { get; set; }
        public System.String REF2_ZIP_CODE { get; set; }
        public System.String REF2_CITY_CODE { get; set; }
        public System.String REF2_COUNTRY_CODE { get; set; }
        public System.String REF2_PHONE_NUMBER { get; set; }
        public Nullable<System.Int32> OTHER_REFERENCES { get; set; }
        public System.String SEC_PAN_GIR_NO { get; set; }
        public System.String SEC_PASSPORT_NUMBER { get; set; }
        public System.String SEC_PASSPORT_PLACE_OF_ISSUE { get; set; }
        public System.String SEC_EMPLOYER_NAME { get; set; }
        public System.String SEC_TELEPHONE_NO { get; set; }
        public Nullable<System.Double> SEC_CREDIT_LIMIT { get; set; }
        public System.String DIRECT_DEBIT_FLAG { get; set; }
        public System.String DIRECT_DEBIT_BRANCH { get; set; }
        public System.String DIRECT_DEBIT_ACCOUNT_NAME { get; set; }
        public System.String DIRECT_DEBIT_ACCOUNT_TYPE { get; set; }
        public System.String DIRECT_DEBIT_ACCOUNT_NUMBER { get; set; }
        public Nullable<System.Int32> ACTUAL_JOB_TENURE { get; set; }
        public System.String OTHER_BANK_BRANCH { get; set; }
        public Nullable<System.Int32> DIRECT_DEBIT_AMOUNT_FLAG { get; set; }
        public System.String CYCOFF_CODE { get; set; }
        public System.String TARIFF_CODE { get; set; }
        public System.String PROFILE_CODE { get; set; }
        public Nullable<System.Int32> DIRECT_DEBIT_PERCENTAGE { get; set; }
        public System.String MICR_CODE { get; set; }
        public System.String PREFERRED_MAILING_ADDRESS { get; set; }
        public System.String PICTURE_CODE { get; set; }
        public System.String PROMO_CODE { get; set; }
        public System.String CUSTOM_LYT_PLAN_ENABLE { get; set; }
        public System.String SEC_PHOTOCARD_APP_IND { get; set; }
        public System.String SEC_PICTURE_CODE { get; set; }
        public System.String CHOICE_WELCOME_GIFT { get; set; }
        public System.String I_AM_INTERESTED_IN { get; set; }
        public System.String FAVOURITE_RESTURANT { get; set; }
        public Nullable<System.Int32> MERCHANT_CAT_CODE_1 { get; set; }
        public Nullable<System.Int32> PTS_DISTRIB_FOR_MCG_1 { get; set; }
        public Nullable<System.Int32> MERCHANT_CAT_CODE_2 { get; set; }
        public Nullable<System.Int32> PTS_DISTRIB_FOR_MCG_2 { get; set; }
        public Nullable<System.Int32> MERCHANT_CAT_CODE_3 { get; set; }
        public Nullable<System.Int32> PTS_DISTRIB_FOR_MCG_3 { get; set; }
        public Nullable<System.Int32> MERCHANT_CAT_CODE_4 { get; set; }
        public Nullable<System.Int32> PTS_DISTRIB_FOR_MCG_4 { get; set; }
        public Nullable<System.Int32> MERCHANT_CAT_CODE_5 { get; set; }
        public Nullable<System.Int32> PTS_DISTRIB_FOR_MCG_5 { get; set; }
        public Nullable<System.Int32> MERCHANT_CAT_CODE_6 { get; set; }
        public Nullable<System.Int32> PTS_DISTRIB_FOR_MCG_6 { get; set; }
        public Nullable<System.Int32> MERCHANT_CAT_CODE_7 { get; set; }
        public Nullable<System.Int32> PTS_DISTRIB_FOR_MCG_7 { get; set; }
        public Nullable<System.Int32> MERCHANT_CAT_CODE_8 { get; set; }
        public Nullable<System.Int32> PTS_DISTRIB_FOR_MCG_8 { get; set; }
        public Nullable<System.Int32> MERCHANT_CAT_CODE_9 { get; set; }
        public Nullable<System.Int32> PTS_DISTRIB_FOR_MCG_9 { get; set; }
        public Nullable<System.Int32> MERCHANT_CAT_CODE_10 { get; set; }
        public Nullable<System.Int32> PTS_DISTRIB_FOR_MCG_10 { get; set; }
        public System.String MNAME { get; set; }
        public System.String CHILD1_NAME { get; set; }
        public System.String CHILD1_DOB { get; set; }
        public System.String NCM_NAME_CHILD2 { get; set; }
        public System.String CHILD2_DOB { get; set; }
        public System.String NCM_DOB_CHILD2 { get; set; }
        public System.String VC_DEGREE { get; set; }
        public System.String VC_UNIVERSITY { get; set; }
        public Nullable<System.Int32> LOS_TOTALYRSEXPERIENCE_N { get; set; }
        public System.String LOS_DESIGNATION_C { get; set; }
        public Nullable<System.Int32> ADDYEAR { get; set; }
        public System.String ALTERNATE_NUBMER { get; set; }
        public System.String PERM_ALTERNATE_NUBMER { get; set; }
        public System.String OFFICE_EMAIL { get; set; }
        public System.String OFFICE_MOBILE { get; set; }
        public System.String PAGER { get; set; }
        public System.String TELEX { get; set; }
        public System.String VEHICLE_OWNERSHIP { get; set; }
        public System.String VEHICLE_REG_NO { get; set; }
        public System.String ISSUER_BANK1 { get; set; }
        public System.String MEMBERSINCE { get; set; }
        public Nullable<System.Int32> CARD1_CREDIT_LIMIT { get; set; }
        public System.String ISSUER_BANK2 { get; set; }
        public System.String CARD2_MEMBER_SINCE { get; set; }
        public Nullable<System.Int32> CARD2_CREDIT_LIMIT { get; set; }
        public Nullable<System.Int32> VC_BRANCH_CD { get; set; }
        public System.String VC_FEE_CD { get; set; }
        public Nullable<System.Int32> N_SMAC { get; set; }
        public System.String PREF_EMAILID { get; set; }
        public System.String NCM_FIN_CUST_ID { get; set; }
        public System.String NCM_ECS_CUST_ID { get; set; }
        public System.String VC_EMPLOYMENT_STATUS { get; set; }
        public System.String LAA_CAMP_TYPE { get; set; }
        public System.String LOS_WHETHER_RESI_C { get; set; }
        public System.String PERM_ADDRESS_CONTACT_PERSON { get; set; }
        public System.String FAX { get; set; }
        public System.String LOS_NATUREOFCOMP_C { get; set; }
        public System.String NCM_ADDON_GENDER { get; set; }
        public System.String BAL_TRANS_NAME { get; set; }
        public System.String NEGATIVE_AREA { get; set; }
        public System.String CUST_PROFILE_FLAG { get; set; }
        public System.String INCOME_DOC_STAT_FLAG { get; set; }
        public System.String APPL_SIGNED_FLAG { get; set; }
        public System.String ISSUERNAME { get; set; }
        public Nullable<System.Int32> RESIDENCETYPE { get; set; }
        public System.String VC_DELIVERY_OP { get; set; }
        public System.String VC_ADDON_PRODUCT { get; set; }
        public System.String VC_BANK_NAME { get; set; }
        public System.String N_AMOUNT { get; set; }
        public System.String VC_ALIAS_NAME { get; set; }
        public System.String FATHERNAME { get; set; }
        public System.String N_CARS_OWN { get; set; }
        public System.String SC_ST_FLAG { get; set; }
        public System.String RENTPERMONTH { get; set; }
        public Nullable<System.Int32> CUST_ID_N { get; set; }
        public System.String LIABILITY { get; set; }
        public System.String STAFF_ID { get; set; }
        public Nullable<System.Double> EL { get; set; }
        public Nullable<System.Double> EAD { get; set; }
        public System.String FEE_CODE { get; set; }
        public Nullable<System.Double> PROB_DEFAULT { get; set; }
        public System.String USER_DEF_FIELD1 { get; set; }
        public System.String USER_DEF_FIELD2 { get; set; }
        public System.String USER_DEF_FIELD3 { get; set; }
        public System.String USER_DEF_FIELD4 { get; set; }
        public System.String USER_DEF_FIELD5 { get; set; }
        public Nullable<System.Int32> EMPL_DESIGNATION { get; set; }
        public System.String EMPL_DEPARTMENT { get; set; }
        public Nullable<System.Int32> EMPL_CURRENT_POSITION { get; set; }
        public System.String SPOUSE_WORKING_STATUS { get; set; }
        public System.String DEMAT_ACCOUNT_NUMBER { get; set; }
        public Nullable<System.Int32> EXISTING_CREDIT_CARD_LIMIT { get; set; }
        public Nullable<System.Double> CREDIT_AS_PERCENT_OF_INCOME { get; set; }
        public System.String MIDDLE_NAME { get; set; }
        public System.String ADDITIONAL_CARD_MIDDLE_NAME { get; set; }
        public System.String ADDITIONAL_GENDER { get; set; }
        public System.String WITNESSED_BY { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE_NOMINEE { get; set; }
        public System.String REFERENCE_EMPLOYEE_ID { get; set; }
        public System.String EMPL_ID { get; set; }
        public System.String APPLICATION_TYPE { get; set; }
        public System.String DSA_CODE { get; set; }
        public System.String VERIFICATION_AGENCY_CODE { get; set; }
        public System.String VOTER_ID { get; set; }
        public System.String STAFF_E_C_NO { get; set; }
        public System.String STAFF_NAME { get; set; }
        public System.String STAFF_BRANCH { get; set; }
        public System.String RECOMMENDED_BY { get; set; }
        public System.String DOM { get; set; }
        public System.String UNIVERSITY { get; set; }
        public System.String FATHER_NAME { get; set; }
        public System.String SPOUSE_MOB_NO { get; set; }
        public System.String RESIDANCE_CHANGED { get; set; }
        public Nullable<System.Double> OTHER_INCOME { get; set; }
        public System.String INCOME_PER_MONTH { get; set; }
        public System.String CUSTOMER_ID { get; set; }
        public System.String TAX_PAID { get; set; }
        public System.String YEAR_TAX_PAID { get; set; }
        public System.String OTHER_BRANCH { get; set; }
        public System.String OTHER_CITY { get; set; }
        public System.String HOUSING_LOAN { get; set; }
        public System.String CAR_LOAN { get; set; }
        public System.String CONSUMER_LOAN { get; set; }
        public System.String BUSINESS_LOAN { get; set; }
        public System.String OTHR_LOAN { get; set; }
        public System.String TYPE_OF_LOAN_OTHERS { get; set; }
        public Nullable<System.Double> LOAN_AMOUNT { get; set; }
        public Nullable<System.Double> CURRENT_OUTSTANDING { get; set; }
        public System.String DURATION_OF_LOAN { get; set; }
        public System.String LOAN_INSTUTION_NAME { get; set; }
        public System.String LOAN_BRANCH { get; set; }
        public System.String BOB_DEBIT_CARD_NO { get; set; }
        public System.String DC_VALID_UPTO { get; set; }
        public System.String CC_BANK_NAME1 { get; set; }
        public System.String CC_NO1 { get; set; }
        public System.String CC_VALID_UPTO1 { get; set; }
        public Nullable<System.Double> CC_CR_LITMIT1 { get; set; }
        public System.String CC_BANK_NAME2 { get; set; }
        public System.String CC_NO2 { get; set; }
        public System.String CC_VALID_UPTO2 { get; set; }
        public Nullable<System.Double> CC_CR_LITMIT2 { get; set; }
        public System.String CC_BANK_NAME3 { get; set; }
        public System.String CC_NO3 { get; set; }
        public System.String CC_VALID_UPTO3 { get; set; }
        public Nullable<System.Double> CC_CR_LITMIT3 { get; set; }
        public System.String SEC2_TITLE { get; set; }
        public System.String SEC2_FIRST_NAME { get; set; }
        public System.String SEC2_MIDDLE_NAME { get; set; }
        public System.String SEC2_LAST_NAME { get; set; }
        public System.String SEC2_EMBOSS_NAME { get; set; }
        public Nullable<System.DateTime> SEC2_BIRTH_DATE { get; set; }
        public System.String SEC2_GENDER { get; set; }
        public System.String SEC2_RELATION { get; set; }
        public System.String REF_NAME1 { get; set; }
        public System.String REF_ADDR1 { get; set; }
        public System.String REF_CITY1 { get; set; }
        public System.String REF_TELEPH1 { get; set; }
        public System.String REF_ZIP_CODE1 { get; set; }
        public System.String REF_NAME2 { get; set; }
        public System.String REF_ADDR2 { get; set; }
        public System.String REF_CITY2 { get; set; }
        public System.String REF_TELEPH2 { get; set; }
        public System.String REF_ZIP_CODE2 { get; set; }
        public Nullable<System.Int32> SEC2_APPLICANT_PROF { get; set; }
        public Nullable<System.Int32> SEC1_APPLICANT_PROF { get; set; }
        public System.String PERM_EMAIL_ID { get; set; }
        public System.String PERM_MOBILE_NUMBER { get; set; }
        public System.String EMPL_EMAIL_ID { get; set; }
        public System.String EMPL_MOBILE_NUMBER { get; set; }
        public System.String REF1_EMAIL_ID { get; set; }
        public System.String REF1_MOBILE_NUMBER { get; set; }
        public System.String RECOMMENDED_BRANCH { get; set; }
        public System.Byte[] APPLICANT_PHOTO { get; set; }
        public Nullable<System.DateTime> _inserted;
        public Nullable<System.DateTime> _updated;
        public System.String _updated_by;
    }
}
